apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Chart.Name }}.{{ .Values.apihost }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-webui
              servicePort: 80
            path: /